### ISSUE TITLE
Change 2D colormaps from seaborn to pcolormesh

### ISSUE THREAD

**Issue by bleutooth65** [mainCSG/QuDiPy#50]
For the charge stability diagrams, switch from seaborn's heatmap to pcolormesh. The axis labels for the pcolormesh are more readible/usable.

**Comment by madisonXschuetze** [comment]
Done!
fixed in commit 2305662b310f2532b5e6ff4220e225998b7b81e3

**Comment by madisonXschuetze** [comment]
Done!
fixed in commit 2305662b310f2532b5e6ff4220e225998b7b81e3
